### ISSUE TITLE
Allow incorrect password to be tried again

### ISSUE THREAD

**Issue by mobileoverlord** [nerves-hub/nerves_hub_cli#110]
Currently, the process will exit with 
```
** (Mix) Invalid password
```

We should allow this to be tried again if the first attempt was incorrect.

**Comment by pcmarks** [comment]
Should the number of attempts allowed be a config value or a module attribute? Or, something else?

**Comment by fhunleth** [comment]
Hardcoding it to 3 tries works for me.

**Comment by fhunleth** [comment]
Addressed in #118.
