### ISSUE TITLE
importing an existing firmware signing key fails

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_cli#161]
if you upload or create a key, and then export it to give to someone else, and try to import it, it will succeed, but give an error from the API when trying to upload it to nerves-hub
```
Unhandled error: {:error, %{"errors" => %{"name" => ["has already been taken"]}}}
```

**Comment by fhunleth** [comment]
Closing since I imported the key and didn't tell you quick enough.
