### ISSUE TITLE
Failed tasks should exit with non zero exit status

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-hub/nerves_hub_cli#66]
Failed commands exit with a 0 exit status. This breaks at least CircleCI.

**Comment by danielspofford** [comment]
Reopening until this gets included in a Hex release.

Hoping to maybe save someone some time resolving that:
* Yes this is an open issue
* Yes there is a fix
* No it is not published to Hex yet

**Comment by fhunleth** [comment]
Released in https://github.com/nerves-hub/nerves_hub_cli/releases/tag/v0.5.1
